Lesson2
Oleg-Psheno/Django_course pull request #2
Opened 2021-01-25 23:27 UTC by Oleg-Psheno

Сделал вывод товаров циклом, но картинка одна на всех)

2021-01-26 19:56 UTC, Vokler requested changes

2021-01-26 19:56 UTC, Vokler commented on mainapp/templates/mainapp/products.html
>                          <div class="card-body">
Поработайте еще с изображением. Это важный момент, я не увидел у вас его в блоке.

2021-01-26 19:59 UTC, Oleg-Psheno commented on mainapp/templates/mainapp/products.html
>                          <div class="card-body">
Хорошо сделаю) я просто думал что это не суть урока, но ок, добавлю в объект products ключ, содержащий ссылку

2021-01-26 22:48 UTC, Oleg-Psheno commented
Сделал отображение картинок, не уверен что  правильно сделал merge  в lesson2

2021-01-26 22:51 UTC, Oleg-Psheno commented
Правильно ли я понимаю, что если я хочу делать 3-й урок при непроверенном 2-м надо новую ветвь делать из lesson2?

2021-01-27 14:08 UTC, Vokler commented
С картинкой порбаботали верно.
Да, если lesson2 еще не смержена, делаете новую ветку из lesson2

2021-01-27 14:08 UTC, merged